spring.application.name=greentrace

spring.data.mongodb.uri=mongodb://localhost:27017/greentrace

server.port=8066

# Sentinel Hub OAuth
sentinel.client.id=f2051149-b4ae-466d-85d9-378992650f2a
sentinel.client.secret=p7CBlSCylI98mORnDmAIGIJLl4zJsQm7

sentinel.token.url=https://services.sentinel-hub.com/oauth/token
sentinel.process.url=https://services.sentinel-hub.com/api/v1/process